version: "3.1"

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      MYSQL_ROOT_PASSWORD: rp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ReviewAPI
    volumes:
      - data:/data/db

volumes:
  data:
